config/routes.rb
Rails.application.routes.draw do

  get 'address/show'
  root to: 'other_pages#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  devise_scope :user do
    get 'my_page', to: 'users/registrations#my_page', as: 'my_page'
  end

  resources :favorites, only: [:create, :destroy]

  resources :articles do
    collection do
      post :confirm
      patch :confirm
    end
  end

  resources :articles do
    member do
      post :confirm
      patch :confirm
    end
  end

  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
  # has_one_attached :image

  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @articles = Article.all.page(params[:page]).per(4)
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).per(4)
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if params[:back]
      render :new
    else
      if @article.save
        redirect_to articles_path, notice: "作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @article = Article.find(params[:id])
    @favorite = current_user.favorites.find_by(article_id: @article.id)
    @comments = @article.comments
    #@comment = @article.comments.build
    @comment = @article.comments.build
    # @comment = Comment.new(article_params)
    # @comment.user_id = current_user.id
    @count = Favorite.where(article_id: @article.id).count
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, alert: ('コメントが削除されました')
  end


  def confirm
    @article = Article.new(article_params)
    @article.id = params[:id]
    render :new if @article.invalid?
  end

  private
  def article_params
    params.require(:article).permit(:title, :content , :id, :image, :image_cache)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  # def choose_new_or_edit
  #   if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
  #     confirm_articles_path
  #   elsif action_name == 'edit'
  #     article_path
  #   end
  # end

  def confirm_new_or_edit
    unless @article.id? # params[:commit] == 'Create Blog'
      articles_path
    else
      article_path
    end
  end

  def confirm_form_method
    @articl.id ? 'patch' : 'post' # 作成時はpost, 編集時は patchを指定
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true , url: confirm_new_or_edit) do |form| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= @article.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">
  <%= form.label :タイトル %>
  <%= form.text_field :title ,class: 'form-control' %>
</div>
<div class="form-group">
  <%= form.label :内容 %>
  <%= form.text_area :content , size: "20x10",class: 'form-control'%>
</div>
<div class="articles_content">
  <%= form.label :画像 %>
  <%= form.file_field :image %>
</div>
<%= form.submit name="登録"%>
<% end %>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

app/views/articles/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @article, local: true , url: articles_path, method: confirm_form_method) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @article.title %></p>
  <p>本文:<%= @article.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/articles/edit.html.erb
<h2>編集する</h2>
<%= render 'form' %>

app/views/articles/index.html.erb
<% if user_signed_in? && current_user.try(:admin?) %>
<%= link_to "マイページ", my_page_path %>
<%= link_to "新規投稿", new_article_path %>
<%= link_to "管理者画面", rails_admin_path %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% elsif user_signed_in? %>
<%= link_to "マイページ", my_page_path %>
<%= link_to "新規投稿", new_article_path %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<%# <%= link_to "新規登録", new_user_registration_path %>
<%# <%= link_to "ログイン", new_user_session_path %>
<% end %>
<% if current_user.try(:admin?) %>
  <h1>管理者用投稿一覧</h1>
<% else %>
  <h1>投稿一覧</h1>
<% end %>

<%= search_form_for @q do |f| %>
  <%= f.label :title_or_content, "検索フォーム" %>
  <%= f.search_field :title_or_content_cont %>
  <%= f.submit "検索" %>
<% end %>

<%# <!-- <td><%= article.comments.size %></td>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">投稿者</th>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
      <th scope="col">画像</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.user.name %></td>
      <td><%= article.title %></td>
      <td><%= article.content %></td>
      <td><%= image_tag article.image.url unless article.image.blank? %></td>
      <td><button type="button" class="btn btn-default"><%= link_to '詳細', article_path(article.id) %></button></td>
      <% if article.user.id == current_user.id %>
      <td><button type="button" class="btn btn-default"><%= link_to "編集", edit_article_path(article.id) %></button></td>
      <td><button type="button" class="btn btn-default"><%= link_to '削除', article_path(article.id), method: :delete %></button></td>
      <% else %>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="pages">
  <p class="page"><%= paginate @articles %></p>
</div>

app/views/articles/new.html.erb
<%= link_to '投稿一覧', articles_path %>
<h2>投稿</h2>
 <%= render 'form' %>

app/views/articles/show.html.erb
<h1>詳細画面</h1>
<p>お気に入り数: <%= @count %></p>
<% unless @article.user_id == current_user.id %>
<% if @favorite.present? %>
<%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
<%= link_to 'お気に入りする', favorites_path(article_id: @article.id), method: :post, class: 'btn btn-primary' %>
<% end %>
<% end %>
<p>タイトル: <%= @article.title %></p>
<p>内容: <%= @article.content %></p>
<p>画像:<%= image_tag @article.image.url , :size => '100x100' unless @article.image.blank? %></p>
<p>コメント数: <%= @article.comments.count %></p>
<p>コメント一覧</p>
<div id="comments_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, article: @article } %>
</div>
<!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
<%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>
<%= link_to '編集', edit_article_path(@article) %> |
<%= link_to '戻る', articles_path %>
</div>
<a class="twitter-timeline" href="https://twitter.com/qYhei6zVyuMFVuX?ref_src=twsrc%5Etfw">Tweets by qYhei6zVyuMFVuX</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>